language: node_js
sudo: required
node_js:
  - "8"

  addons:
  chrome: stable

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9876 http://localhost &